CREATE TABLE `oa_user_account` (
  `id` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '用户id编号',
  `sales_volume_id` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '当前申请销售额id',
  `flow_id` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '流程id',
  `branch_quota` decimal(19,2) NOT NULL COMMENT '每月可支配额',
  `pool_funds` decimal(19,2) NOT NULL COMMENT '资金池',
  `cost_incurred` decimal(19,2) NOT NULL COMMENT '当月发生费用',
  `spare_a` decimal(19,2) NOT NULL COMMENT '备用字段1',
  `spare_b` decimal(19,2) NOT NULL COMMENT '备用字段2',
  `spare_c` decimal(19,2) NOT NULL COMMENT '备用字段3',
  `string_a` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '备用字符1',
  `string_b` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '备用字符2',
  `string_c` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '备用字符3',
  `flag` char(1) COLLATE utf8_bin NOT NULL DEFAULT '0' COMMENT '是否可用(冻结)',
  `create_by` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '创建者',
  `create_date` datetime NOT NULL COMMENT '创建时间',
  `update_by` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '更新者',
  `update_date` datetime NOT NULL COMMENT '更新时间',
  `remarks` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '备注信息',
  `del_flag` char(1) COLLATE utf8_bin NOT NULL DEFAULT '0' COMMENT '删除标记',
  `status` varchar(4) COLLATE utf8_bin DEFAULT NULL COMMENT '(默认0,1.申请中，2.通过.-1驳回)',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户账户';
CREATE TABLE `oa_user_account_log` (
  `id` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '用户id编号',
  `sales_volume_id` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '当前申请销售额id',
  `branch_quota` decimal(19,2) NOT NULL COMMENT '每月可支配额',
  `pool_funds` decimal(19,2) NOT NULL COMMENT '资金池',
  `cost_incurred` decimal(19,2) NOT NULL COMMENT '当月发生费用',
  `spare_a` decimal(19,2) NOT NULL COMMENT '备用字段1',
  `spare_b` decimal(19,2) NOT NULL COMMENT '备用字段2',
  `spare_c` decimal(19,2) NOT NULL COMMENT '备用字段3',
  `string_a` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '备用字符1',
  `string_b` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '备用字符2',
  `string_c` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '备用字符3',
  `flag` char(1) COLLATE utf8_bin NOT NULL DEFAULT '0' COMMENT '是否可用(冻结)',
  `create_by` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '创建者',
  `create_date` datetime NOT NULL COMMENT '创建时间',
  `update_by` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '更新者',
  `update_date` datetime NOT NULL COMMENT '更新时间',
  `remarks` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '备注信息',
  `del_flag` char(1) COLLATE utf8_bin NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='记录月结用户账户';
CREATE TABLE `oa_user_pro_settlement` (
  `id` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '用户id编号',
  `pro_id` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '项目id',
  `person_liable_user` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '销售',
  `settlement` decimal(19,2) NOT NULL COMMENT '结算费用',
  `expenditure` decimal(19,2) NOT NULL COMMENT '支出费用',
  `create_by` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '创建者',
  `create_date` datetime NOT NULL COMMENT '创建时间',
  `update_by` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '更新者',
  `update_date` datetime NOT NULL COMMENT '更新时间',
  `remarks` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '备注信息',
  `del_flag` char(1) COLLATE utf8_bin NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='项目费用结算';
CREATE TABLE `oa_user_sales_volume` (
  `id` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '用户id编号',
  `flow_id` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '流程id',
  `sales_volume` decimal(19,2) NOT NULL COMMENT '销售额',
  `status` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT '状态(默认0,1.申请中，2.通过.-1驳回)',
  `flag` char(1) COLLATE utf8_bin NOT NULL DEFAULT '0' COMMENT '是否可用(冻结)',
  `create_by` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '创建者',
  `create_date` datetime NOT NULL COMMENT '创建时间',
  `update_by` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '更新者',
  `update_date` datetime NOT NULL COMMENT '更新时间',
  `remarks` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '备注信息',
  `del_flag` char(1) COLLATE utf8_bin NOT NULL DEFAULT '0' COMMENT '删除标记',
  `uotaRatio` varchar(5) COLLATE utf8_bin DEFAULT '0' COMMENT '使用销售额比例',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='申请销售额';